### ISSUE TITLE
incorrect warning about missing write permissions

### ISSUE THREAD

**Issue by ltalirz** [uchida/ansible-miniconda-role#17]
This occurs using recent miniconda versions, e.g.:
```yaml
   - role: uchida.miniconda
      tags: miniconda
      vars:
        miniconda_python: 3
        miniconda_version: 4.6.14
        miniconda_prefix: "{{ vm_codes_folder }}/miniconda"
        miniconda_env:
          name: addis
          channels:
            - conda-forge
          dependencies:
            - rdkit=2019.03.2.0
            - ase=3.17.0
            - scipy=1.3.0
            - matplotlib=3.1.0
            - jupyter=1.0.0
```

The **first** time I run the role (and only the first time), I get the following error:
```
TASK [uchida.miniconda : conda environment addis is created] *******************
fatal: [default]: FAILED! => changed=true
  cmd:
  - ${HOME}/codes/miniconda/bin/conda
  - env
  - create
  - -f
  - /tmp/addis-environment.yml
  - -q
  delta: '0:00:00.487782'
  end: '2019-06-02 22:41:45.465240'
  msg: non-zero return code
  rc: 1
  start: '2019-06-02 22:41:44.977458'
  stderr: |2-

    NotWritableError: The current user does not have write permissions to a required path.
      path: /home/max/codes/miniconda/envs/.conda_envs_dir_test
      uid: 1001
      gid: 100

    If you feel that permissions on this path are set incorrectly, you can manually
    change them by executing

      $ sudo chown 1001:100 /home/max/codes/miniconda/envs/.conda_envs_dir_test

    In general, it's not advisable to use 'sudo conda'.
  stderr_lines:
  - ''
  - 'NotWritableError: The current user does not have write permissions to a required path.'
  - '  path: /home/max/codes/miniconda/envs/.conda_envs_dir_test'
  - '  uid: 1001'
  - '  gid: 100'
  - ''
  - If you feel that permissions on this path are set incorrectly, you can manually
  - change them by executing
  - ''
  - '  $ sudo chown 1001:100 /home/max/codes/miniconda/envs/.conda_envs_dir_test'
  - ''
  - In general, it's not advisable to use 'sudo conda'.
  stdout: ''
  stdout_lines: <omitted>
	to retry, use: --limit @/Users/leopold/Personal/Postdoc-MARVEL/repos/quantum-mobile/playbook.retry
```
When I go to the directory, everything seems fine in terms of permissions.
When I run the role a **second** time, it completes without warnings.
